### ISSUE TITLE
Strange grey padding embedded in Sphinx with jupyter-execute

### ISSUE THREAD

**Issue by banesullivan** [jupyter-widgets/ipyleaflet#1059]
The [docs for localtileserver](https://localtileserver.banesullivan.com/) have this odd looking grey padding on the tile layers:

<img width="861" alt="Screen Shot 2022-09-29 at 9 35 36 PM" src="https://user-images.githubusercontent.com/22067021/193184843-d2f7e81b-44bc-40bf-9460-fb0147749c2d.png">

I'm not doing anything fancy here, just using `jupyter-execute` to embed the widgets in the docs like you all do here. 

I'm curious if anyone has insight into what might be going wrong here?

**Comment by martinRenou** [comment]
It's really odd! That's not what I see on my side:

![Screenshot from 2022-09-30 08-57-41](https://user-images.githubusercontent.com/21197331/193209931-6ba8bff9-61c8-4bcf-a536-df028acf5d82.png)

Are you using some custom CSS plugin in your browser? ([dark-reader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=en) or similar)

I see a one pixel padding since a couple of years, but it's definitely not specific to ipyleaflet because I see it in the LeafletJS docs too.

**Comment by davidbrochart** [comment]
I don't see that either.
And the San Francisco tiles are not displayed in your case @banesullivan ?

**Comment by banesullivan** [comment]
Well this is super strange!!! Now I'm not seeing it where I was for a few days on both my desktop (chrome and safari) and my phone (mobile safari). The interesting trend is that it was night time when I was working on this stuff and I didn't check during the day, so I suspect it's some dark-mode CSS thing.

I'm going to close this issue as it's got to be something wacky with the CSS on my site and/or dark mode being enabled.

> And the San Francisco tiles are not displayed in your case

Well, this was me debugging to make sure it wasn't the `TileLayer` with the raster and that it was happening with the basemap

Thank you both for checking on your sides!
