### ISSUE TITLE
ipyleaflet is broken (missing file on CDN)

### ISSUE THREAD

**Issue by naschmitz** [jupyter-widgets/ipyleaflet#1192]
The jupyter-leaflet@0.19 implementation no longer exists on the jsdelivr CDN. I get a 404 when loading https://cdn.jsdelivr.net/npm/jupyter-leaflet@0.19/dist/index.js. ipyleaflet was working fine yesterday, and today it's not.

**Comment by giswqs** [comment]
@martinRenou @maartenbreddels it seems the newest ipyleaflet v0.19.0 is broken. It doesn't work on Colab

**Comment by maartenbreddels** [comment]
@iisakkirotko do you want to take a look at this?

**Comment by maartenbreddels** [comment]
The issue was fixed in https://github.com/jupyter-widgets/ipyleaflet/commit/fd02487e1402de6f947b58d79720ebda27cf593d, and I released version 0.19.1, which contains this fix.

Due to the loose dependency in ipyleaflet (using semver ^0.19.0), voila will pick up 0.19.1 from the CDN, so you might not need to upgrade.

**Comment by giswqs** [comment]
Thank you very much for fixing it. I can confirm that now ipyleaflet works properly on Colab

**Comment by martinRenou** [comment]
Thanks a lot @maartenbreddels !
