### ISSUE TITLE
Changing position of some controls doesn't work

### ISSUE THREAD

**Issue by kgiacobbi** [jupyter-widgets/ipyleaflet#367]
Hello, 
I saw that is not possible to change the position of those controls on a map. 
The FullScreenControl is always on the top left corner and LayersControl on the top right corner.
```
import ipyleaflet as lf
m = lf.Map()
m.add_control(lf.FullScreenControl(position='bottomleft'))
m.add_control(lf.LayersControl(position='bottomleft'))
m
```
![capture_controls](https://user-images.githubusercontent.com/49714549/58323552-9b3e8900-7e24-11e9-96aa-1b3664bf2b98.png)

I saw that the control has it option `position = 'bottomleft'` but i think the option is not passed at the JS side so it keeps the default value.

**Comment by martinRenou** [comment]
We might be doing something wrong in ipyleaflet, but because it works with some controls, I suppose this is more likely an issue with upstream packages (https://github.com/Leaflet/Leaflet.fullscreen, etc). We need to figure it out. We should either open feature requests upstream or open PRs upstream for fixing this issue. Or we could try to find workarounds.

**Comment by martinRenou** [comment]
Your PR fixed this issue apparently, I was wrong on my last comment, it was indeed a bug in ipyleaflet. Thanks a lot!
