### ISSUE TITLE
Release 0.10.8 not in stable branch

### ISSUE THREAD

**Issue by chbrandt** [jupyter-widgets/ipyleaflet#390]
Hi @martinRenou, I see you released the version [0.10.8](https://github.com/jupyter-widgets/ipyleaflet/commit/7a54383e589c74038c144f19f7653b7f8ded2776) a couple of hours ago, but this commit is not in the `stable` branch (yet).
Did you just miss that merge or is there a particular meaning to have a release (candidate maybe?) in master but not in stable?
I ask because I will touch such code base (python+js+jupyter) for the very first time and would like to start from a stable release.
Cheers

**Comment by martinRenou** [comment]
Hi @chbrandt, thanks for the update. I will update the `stable` branch.

Note that the `stable` branch is only used for having a stable branch upon which running the Binder (the binder link is https://mybinder.org/v2/gh/jupyter-widgets/ipyleaflet/stable), so that if we break the `master` branch, the Binder example still works.

If you want to work on ipyleaflet for opening Pull Requests, it's better to create a new branch from `master`, not from `stable`.

**Comment by chbrandt** [comment]
OK, cool. Got it. Thanks
