### ISSUE TITLE
Guidance on understanding the code

### ISSUE THREAD

**Issue by chbrandt** [jupyter-widgets/ipyleaflet#395]
I'm starting with ipyleaflet, but I'm having some difficulties in using it; my obstacles present themselves in two different levels: (1) sometimes the documentation is not clear, (2) the source code is quite obscure to me.

For example, I wanted to use the Image overlay, which apparently is/will be documented here: https://ipyleaflet.readthedocs.io/en/latest/api_reference/image_video_overlay.html . Not finding the documentation there I went into the source code to figure it out, https://github.com/jupyter-widgets/ipyleaflet/blob/88cb4b83f149b348bd69936fb9d07b8c44dea40e/ipyleaflet/leaflet.py#L283 . But the [source code](https://github.com/jupyter-widgets/ipyleaflet/blob/88cb4b83f149b348bd69936fb9d07b8c44dea40e/ipyleaflet/leaflet.py#L283) is not really clear to me. I know, it is my ignorance.

My question is -- hopefully -- simple and welcome: do you have any guidelines/documentation for new developers? As a user, I would like to contribute maybe at the documentation level; and if I have the brains -- since I have some experience with Leaflet -- I will do my best to give it back at the code level.

Thanks.

**Comment by martinRenou** [comment]
Hi,

Well, as you can see, the Python code is quite simple. ipyleaflet is based on ipywidgets which is based on traitlets, I suggest you check how traitlets works by reading its [documentation](https://traitlets.readthedocs.io).

The `ImageOverlay` class only has 3 attributes, the `url` to the image you want to use (it can be a dataurl), the `bounds` which is the SW and NE corners of the image, and the `attribution` which is just a string value containing information about where this image comes from/who has got the rights on this image.

Since you have some experience with Leaflet, you should see that most of the times, the Python classes only exposes the Leaflet API. Whenever you change an attribute Python side, the ipywidgets logic takes care of sending the right events to the JavaScript side, which will update the associated attribute.

All the JavaScript code is here: https://github.com/jupyter-widgets/ipyleaflet/tree/88cb4b83f149b348bd69936fb9d07b8c44dea40e/js/src

**Comment by chbrandt** [comment]
Cool, thanks @martinRenou
