### ISSUE TITLE
Scale bar

### ISSUE THREAD

**Issue by eslrgs** [jupyter-widgets/ipyleaflet#491]
Hi, 

Is there a way to add a scale bar to an ipyleaflet map?

**Comment by martinRenou** [comment]
Hi! Thanks for opening an issue.

It should come in the next release ;) #492

**Comment by eslrgs** [comment]
Thanks! One more thing..where do you find the marker styles that are able to be used?

Great programme by the way!

**Comment by martinRenou** [comment]
Thanks!

If you are talking about [AwesomeIcon](https://ipyleaflet.readthedocs.io/en/latest/api_reference/awesome_icon.html), you can find available icons on the [Font Awesome page](https://fontawesome.com/v4.7.0/icons/). For background color and marker color the following is available: `'white', 'red', 'darkred', 'lightred', 'orange', 'beige', 'green', 'darkgreen', 'lightgreen', 'blue', 'darkblue', 'lightblue', 'purple', 'darkpurple', 'pink', 'cadetblue', 'white', 'gray', 'lightgray', 'black'`.

Otherwise, you can use icons from images, see https://ipyleaflet.readthedocs.io/en/latest/api_reference/icon.html.

A marker without an icon will be rendered blue, and cannot be styled at the moment.

**Comment by eslrgs** [comment]
Thanks for all the help!
