### ISSUE TITLE
Marker Attribute Title 

### ISSUE THREAD

**Issue by pepeto** [jupyter-widgets/ipyleaflet#676]
Documentation says:
title | “” | Text for the browser tooltip that appear on marker hover (no tooltip by default)

I can't find an example for this and I can't see any tooltip when I pass the mouse over the marker. 

What's the right way to implement it?

Thank you!

**Comment by sackh** [comment]
looks like there is some bug with this functionality. for now, you can use an alternate way to show pop up using - https://ipyleaflet.readthedocs.io/en/latest/api_reference/popup.html

**Comment by davidbrochart** [comment]
Fixed in #677

**Comment by martinRenou** [comment]
I suppose there is a misunderstanding here. This issue is about the Marker class's title property, The title is a browser feature that shows a small popup (not an actual Leaflet Popup) when the mouse is over an HTML element. In LeafletJS it's this property that we are exposing: https://leafletjs.com/reference-1.6.0.html#marker-title, we should not do anything about it, we should let LeafletJS handle it.

I think the #677 PR should be reverted and not released.

> I can't find an example for this and I can't see any tooltip when I pass the mouse over the marker.

I don't recall there is an example about it on the repo but you can try it. If it does not work it might be an issue on LeafletJS side, or we don't properly react on title change, so there might be an issue there.

On another note, you can assign a Popup yourself, but that would be an actual Popup instance this time. The look and feel is not the same.

**Comment by martinRenou** [comment]
Other docs about the title attribute: https://www.w3schools.com/tags/att_title.asp
