### ISSUE TITLE
How to remove the Layers when i created polygon use DrawControl?

### ISSUE THREAD

**Issue by tracegyx** [jupyter-widgets/ipyleaflet#68]
I know that there is a button on map and use it to delete the layers, but i want delete the layers use code, so what should i do?
![e9b495c8-e6ee-499c-95ff-0aa323e40d12](https://user-images.githubusercontent.com/21274507/28400980-58da5550-6d49-11e7-9a0a-843d0870b39d.png)

**Comment by GriffinLane** [comment]
I too am looking for a feature that will allow me to delete previous rectangles and/or limit their quantity.  Bump +1

**Comment by martinRenou** [comment]
It's actually not that easy to implement. First, there is a bug in ipyleaflet, the `FeatureGroup` class should inherit from `LayerGroup` class, like in `Leaflet`: https://github.com/Leaflet/Leaflet/blob/e5a3d5ecc360af77e291451172c60d4e3807cf72/src/layer/FeatureGroup.js#L26 so that we could have access to `add_layer`, `remove_layer` methods.
I open a PR for this first issue, but even after this fix, it will still not be possible to fix your issue.

The `DrawControl` widget owns a `layer` attribute which is a `FeatureGroup` instance, you can add new layers (rectangle, markers...) to this `layer` attribute from the python side and it works fine. 

BUT if a new layer has been added to this featuregroup from the javascript side (for instance when drawing a rectangle with your mouse), the list of layers won't be synchronized anymore between the python and javascript. So you won't have access to new added layers from the python side, which is why it's not possible with the current implementation of `FeatureGroup` to implement your request.

However, I found a workaround so that it's possible to remove drawings, hiding the complexity of the `FeatureGroup` from the python side, I'll open a PR soon.

**Comment by martinRenou** [comment]
My PR removes the `layer` attribute of `DrawControl`, but as `FeatureGroup` was not working, I think it's safe to say that nobody was using it
