### ISSUE TITLE
Add fitBounds method for map

### ISSUE THREAD

**Issue by ledovsky** [jupyter-widgets/ipyleaflet#96]
Hi, thanks for the lib. It's awesome!

I havn't found a way to init a map with certain bbox coords. While there is fitBounds() method in Leaflet documentation http://leafletjs.com/reference-1.3.0.html#map-fitbounds

**Comment by SylvainCorlay** [comment]
@ledovsky this is actually a tricky question because multiple views of the same map can exist, especially with the JupyterLab integration.

Now the bounds of a map correspond to the smallest rectangle covering the geographical area shown by all the views of the same map.

For a fitbounds to make sense, we would probably want to smallest view to be able to contain the specified bounds...

What d o you think?
